// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7jwi-6HMDqfa6jwHd4xEWyvdi9byBKIU',
    appId: '1:176152339867:web:4e51468234e48d910f2d3e',
    messagingSenderId: '176152339867',
    projectId: 'elevate-d14ed',
    authDomain: 'elevate-d14ed.firebaseapp.com',
    storageBucket: 'elevate-d14ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc7zlkNfczPRULW440nyE0zHpho5ZkgLM',
    appId: '1:176152339867:android:87931a391617eec80f2d3e',
    messagingSenderId: '176152339867',
    projectId: 'elevate-d14ed',
    storageBucket: 'elevate-d14ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhlfZrPEb5rtwq0XHY9hqjLeCQtq6r618',
    appId: '1:176152339867:ios:f0acad505502f9980f2d3e',
    messagingSenderId: '176152339867',
    projectId: 'elevate-d14ed',
    storageBucket: 'elevate-d14ed.firebasestorage.app',
    iosBundleId: 'com.example.elevateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhlfZrPEb5rtwq0XHY9hqjLeCQtq6r618',
    appId: '1:176152339867:ios:f0acad505502f9980f2d3e',
    messagingSenderId: '176152339867',
    projectId: 'elevate-d14ed',
    storageBucket: 'elevate-d14ed.firebasestorage.app',
    iosBundleId: 'com.example.elevateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7jwi-6HMDqfa6jwHd4xEWyvdi9byBKIU',
    appId: '1:176152339867:web:2e55dda9731933b80f2d3e',
    messagingSenderId: '176152339867',
    projectId: 'elevate-d14ed',
    authDomain: 'elevate-d14ed.firebaseapp.com',
    storageBucket: 'elevate-d14ed.firebasestorage.app',
  );
}
